# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactapp

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'reactapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactappTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

target 'reactapp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactapp-tvOS
end
